fix: modify rbush package import
openlayers/openlayers pull request #11474
Opened 2020-08-25 11:48 UTC by haasz

Fixes #11473

2020-08-25 12:11 UTC, ahocevar requested changes
Good catch, thanks @haasz!

2020-08-25 12:11 UTC, ahocevar approved these changes

2020-08-25 12:12 UTC, merged

2021-02-22 10:29 UTC, walkermatt commented
Hi, I've created https://github.com/mourner/rbush/pull/114 to transpile ES6 features except import/ export in the rbush module. Currently the package specifies `module: 'index.js'`, `index.js` includes ES6 syntax such as `class` which is what prompted #10385.

If https://github.com/mourner/rbush/pull/114 is merged then we shouldn't need any changes in OpenLayers but we will gain IE11 support.

2023-03-25 19:55 UTC, ahocevar commented
> If https://github.com/mourner/rbush/pull/114 is merged then we shouldn't need any changes in OpenLayers but we will gain IE11 support.

This is obsolete now that we don't support IE any more and ship untranspiled modules.