Make webpack dev server run with current version
openlayers/openlayers pull request #11658
Opened 2020-10-18 08:42 UTC by MoonE

webpack-dev-server seems to be no longer available.
https://github.com/webpack/webpack-dev-server/issues/2029#issuecomment-585207461

2020-10-18 16:42 UTC, ahocevar requested changes
Thanks, @MoonE. In addition to the change you already made, it would be good to run

    npm uninstall --save-dev webpack-dev-server

and commit and push the resulting changes in `package.json` and `package-lock.json`.

2020-10-18 17:30 UTC, MoonE commented
It won't run without webpack-dev-server installed. i guess they only changed how it is started.
> [webpack-cli] Promise rejection: Error: You need to install 'webpack-dev-server' for running 'webpack serve'.

Below is the error I get with the current main branch:
```
webpack-dev-server --config examples/webpack/config.js --mode development --watch

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- ~/openlayers/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (~/openlayers/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/openlayers/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

2020-10-18 17:48 UTC, ahocevar approved these changes
Thanks for the explanations, @MoonE.

2020-10-18 17:48 UTC, merged

2021-04-25 05:38 UTC, Juniad9421 commented
boilerplate@1.0.0 dev-server                                                                                          
 webpack-dev-server                                                                                                    
                                                                                                                       
ode:internal/modules/cjs/loader:943                                                                                    
 throw err;                                                                                                            
 ^                                                                                                                     
                                                                                                                       
rror: Cannot find module 'webpack-cli/bin/config-yargs'                                                                
equire stack:                                                                                                          
 F:\Web Development\JS\boilerplate\node_modules\webpack-dev-server\bin\webpack-dev-server.js                           
   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)                                       
   at Function.Module._load (node:internal/modules/cjs/loader:773:27)                                                  
   at Module.require (node:internal/modules/cjs/loader:1012:19)                                                        
   at require (node:internal/modules/cjs/helpers:93:18)                                                                
   at Object.<anonymous> (F:\Web Development\JS\boilerplate\node_modules\webpack-dev-server\bin\webpack-dev-server.js:6
:1)                                                                                                                    
   at Module._compile (node:internal/modules/cjs/loader:1108:14)                                                       
   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)                                         
   at Module.load (node:internal/modules/cjs/loader:988:32)                                                            
   at Function.Module._load (node:internal/modules/cjs/loader:828:14)                                                  
   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {                             
 code: 'MODULE_NOT_FOUND',                                                                                             
 requireStack: [                                                                                                       
   'F:\\Web Development\\JS\\boilerplate\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'                
 ]          
                                                                                                           
/***** Specification *******/                                                                                                                       

"webpack": "^5.35.1"
"webpack-cli": "^4.6.0",
"webpack-dev-server": "^3.11.2"

2021-04-25 05:40 UTC, Juniad9421 commented
hi ! i was creating custom Dev-server for my project so this type error occurs  .. Please tell me solution for this bug

2021-07-10 20:46 UTC, thfrei commented
I come from this issue: https://github.com/webpack/webpack-dev-server/issues/2029#issuecomment-711416810

Still, webpack-dev-server does not work with webpack-cli v4.x

Downgrade webpack-cli to v3.x

```
> webpack-dev-server --open --config webpack.dev.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /workspace/ixdfnvas/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/infsdfcanvas/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/infinisdfas/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infsdfas@0.0.6 dev: `webpack-dev-server --open --config webpack.dev.js "--public" "8080-cfd.io:443"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infinite-drawing-canvas@0.0.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-07-10T20_42_58_522Z-debug.log
```