Do not set projection extent in WMTS optionsFromCapabilities unless matrix set projection is also supported
openlayers/openlayers pull request #11792
Opened 2020-12-01 17:39 UTC by mike-000

Fixes #11738

If the matrix set does not contain a useable projection an error is thrown by ol/tilegrid/WMTS.createFromCapabilitiesMatrixSet (where an assertion might be nicer than `Cannot read property 'getMetersPerUnit' of undefined`)  It seems inappropriate to set the extent of the projection supplied in the WMTS optionsFromCapabilities config options to the matrix extent unless it is going to be used.

2020-12-04 19:07 UTC, ahocevar requested changes
This fix is a bit problematic, because it only makes the underlying problem less obvious. A better fix would be if `optionsFromCapabilities()` would not set an extent on the projection at all. For example by creating a new `Projection` object, which is returned as `projection` property in the options output.

2020-12-05 14:51 UTC, ahocevar reviewed
Thanks, @mike-000. This looks good now. Would you be able to add a test to make it perfect?

2020-12-06 11:47 UTC, ahocevar reviewed
Instead of adding a tile matrix set to `test/spec/ol/format/wmts/ogcsample.xml`, could you please create a new wmts capabilities doc for the new tests? Maybe a real-life one from Ordnance Survey?

2020-12-06 15:01 UTC, mike-000 commented
I inadvertently chose a layer with TileMatrixSetLimits for a test and found the limits were reflected in the projection extent.  Beyond the scope of this PR but perhaps a new issue as that might not be desirable, for example if multiple layers were to be used as in https://labs.os.uk/public/os-data-hub-examples/os-maps-api/zxy-example-change-style (but using EPSG:27700 and WMTS with the Leisure layer) the outcome could depend on the order the layers were defined.

2020-12-06 16:19 UTC, ahocevar commented
> I inadvertently chose a layer with TileMatrixSetLimits for a test and found the limits were reflected in the projection extent. Beyond the scope of this PR but perhaps a new issue as that might not be desirable, for example if multiple layers were to be used

Absolutely right @mike-000, that's not desirable.

2020-12-06 16:39 UTC, ahocevar commented
And thinking about it more, I feel like having the `optionsFromCapabilities` function set an extent on a projection at all is wrong. Since `optionsFromCapabilities` uses `WMTSTileGrid#createFromCapabilitiesMatrixSet` to create a suitable tilegrid (with the proper extent), I see no reason why #9590 added this if-block in the first place:

https://github.com/mloskot/openlayers/blob/98e8bec3709364b5fd14dd71a4e4e72dcf4ae1c9/src/ol/source/WMTS.js#L396-L398

@mloskot Can you maybe shed some light on this? All tests continue to pass with that block removed.

@mike-000 I'm leaving this pull request open until we hear back from @mloskot.

2020-12-06 21:59 UTC, mike-000 commented
Creating new projections will mitigate against setting the extent of a single shared projection too small, but I agree that setting projection extents based on the tile grid can be meaningless.  Esri's tile grid for EPSG:27700 as used in the Raster Reprojection example is much larger than the normal projection extent with the OS Overview map reduced to a few pixels in one corner of the 0/0/0 tile.  If used as the limits for reprojection that would probably cause errors.

![image](https://user-images.githubusercontent.com/49240900/101293623-cd97b780-380b-11eb-96a9-9863798bd393.png)

2020-12-07 11:53 UTC, mloskot commented
@ahocevar TBH, it's been a while and I can't remember exactly. I think I added that as a fallback, a safety net.

2021-04-27 12:38 UTC, mike-000 commented
@ahocevar How to you wish to proceed?  The current code still sets an extent on the primary projection object which seems wrong in any situation.  Either a new PR to remove that line and always leave it to the application to set extents, or this best attempt at setting an extent on a new copy of the projection which may not be perfect but perhaps better than doing nothing?  A rebase was needed due to #11405 but that means my tests will need to be revised.

2021-04-27 13:31 UTC, ahocevar commented
I'd say leave setting the extent to the application. If I'm not mistaken, that extent on the projection is only relevant for `wrapX`.

2021-05-01 11:51 UTC, closed without merging