Fix Modify interaction with hitDetection
openlayers/openlayers pull request #12237
Opened 2021-04-23 07:42 UTC by M393

Fixes Modify configured with hit detection.
See #12235

Hit detection should ignore any RenderFeatures and features not in the configured source / collection.

2021-04-23 07:43 UTC, M393 commented
This most likely doesn't fix what @mike-000 reported in https://github.com/openlayers/openlayers/issues/12235#issuecomment-825086303

2021-05-17 06:08 UTC, M393 commented on src/ol/interaction/Modify.js
> +            this.features_.getArray().includes(feature)
Thanks @mike-000, changed it.

2021-06-16 17:31 UTC, ahocevar reviewed
I don't think it is necessary to skip render features. `getFlatCoordinates` could be used instead of `getCoordinates` to support both features and render features.

2021-06-17 08:47 UTC, ahocevar commented
> This most likely doesn't fix what @mike-000 reported in [#12235 (comment)](https://github.com/openlayers/openlayers/issues/12235#issuecomment-825086303)

That issue is fixed by #12408.

2021-06-17 08:54 UTC, ahocevar requested changes
Thanks @M393! Please modify this pull request according to my suggestions - we can easily handle render features too by using `getFlatCoordinates()` instead of `getCoordinates()`.

2021-06-21 10:35 UTC, ahocevar approved these changes
Thanks, @M393

2021-06-21 10:36 UTC, merged