Fix layer canvas reuse
openlayers/openlayers pull request #12306
Opened 2021-05-12 13:51 UTC by M393

Fixes #12305

2021-05-17 08:59 UTC, ahocevar requested changes
This change would break rendering in a worker, where `document.createElement()` is not available. For this reason, `ol/layer/renderer/canvas/TileLayer.js` and `ol/layer/renderer/canvas/ImageLayer.js` call `createTransformString()` before calling `useContainer()`. But this is missing for `ol/layer/renderer/canvas/VectorLayer.js`.

I agree that the right place to normalize the transform string would be `toString()` like in your pull request, but the implementation should be changed to handle the case where we are in a worker, like in `createTransformString()`. If you can change `toString()` this way, the `createTransformString()` function and its call sites can probably be removed.

2021-05-17 19:43 UTC, MoonE commented
Return with assignment will return the original value.

2021-05-18 13:02 UTC, ahocevar requested changes
I'd suggest to rename `dummyNode` to `transformStringDiv`. Other than that, this pull request looks good.

2021-05-18 13:02 UTC, ahocevar commented on src/ol/transform.js
> +let dummyNode;
```suggestion
let transformStringDiv;
```

2021-05-18 13:02 UTC, ahocevar commented on src/ol/transform.js
> +  const node = dummyNode || (dummyNode = document.createElement('div'));
```suggestion
  const node = transformStringDiv || (transformStringDiv = document.createElement('div'));
```

2021-05-23 09:03 UTC, ahocevar approved these changes

2021-05-23 09:03 UTC, merged

2021-05-23 09:03 UTC, ahocevar commented
Thanks, @M393