Fix WMTS wrapX detection if WGS84BoundingBox is not set
openlayers/openlayers pull request #12409
Opened 2021-06-17 10:22 UTC by M393

There is an error thrown in `optionsFromCapabilities` when WGS84BoundingBox is not set in the layer config.
This sets wrapX to false in this case.

2021-06-17 11:54 UTC, M393 commented
Here's the xml I'm parsing:
<details>
<summary>File content</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>\n<Capabilities xmlns="http://www.opengis.net/wmts/1.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd" version="1.0.0">
    <ows:ServiceIdentification>
        <ows:ServiceType>OGC WMTS</ows:ServiceType>
        <ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>
    </ows:ServiceIdentification>
    <ows:ServiceProvider>
        <ows:ServiceContact>
            <ows:ContactInfo/>
        </ows:ServiceContact>
    </ows:ServiceProvider>
    <ows:OperationsMetadata>
        <ows:Operation name="GetCapabilities">
            <ows:DCP>
                <ows:HTTP>
                    <ows:Get xlink:href="http://localhost/services/wmts?">
                        <ows:Constraint name="GetEncoding">
                            <ows:AllowedValues>
                                <ows:Value>KVP</ows:Value>
                            </ows:AllowedValues>
                        </ows:Constraint>
                    </ows:Get>
                </ows:HTTP>
            </ows:DCP>
        </ows:Operation>
        <ows:Operation name="GetTile">
            <ows:DCP>
                <ows:HTTP>
                    <ows:Get xlink:href="http://localhost/services/wmts?">
                        <ows:Constraint name="GetEncoding">
                            <ows:AllowedValues>
                                <ows:Value>KVP</ows:Value>
                            </ows:AllowedValues>
                        </ows:Constraint>
                    </ows:Get>
                </ows:HTTP>
            </ows:DCP>
        </ows:Operation>
        <ows:Operation name="GetFeatureInfo">
            <ows:DCP>
                <ows:HTTP>
                    <ows:Get xlink:href="http://localhost/services/wmts?">
                        <ows:Constraint name="GetEncoding">
                            <ows:AllowedValues>
                                <ows:Value>KVP</ows:Value>
                            </ows:AllowedValues>
                        </ows:Constraint>
                    </ows:Get>
                </ows:HTTP>
            </ows:DCP>
        </ows:Operation>
    </ows:OperationsMetadata>
    <Contents>
        <Layer>
            <ows:Title>streets</ows:Title>
            <ows:Identifier>streets</ows:Identifier>
            <Style isDefault="true">
                <ows:Identifier>default</ows:Identifier>
            </Style>
            <Format>image/png; mode=8bit</Format>
            <TileMatrixSetLink>
                <TileMatrixSet>1x</TileMatrixSet>
                <TileMatrixSetLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:0</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>0</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>0</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:1</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>1</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>1</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:2</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>3</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>3</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:3</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>7</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>7</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:4</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>15</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>15</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:5</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>31</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>31</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:6</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>63</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>63</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:7</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>127</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>127</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:8</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>255</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>255</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:9</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>511</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>511</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:10</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>1023</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>1023</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:11</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>2047</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>2047</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:12</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>4095</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>4095</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:13</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>8191</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>8191</MaxTileCol>
                    </TileMatrixLimits>
                    <TileMatrixLimits>
                        <TileMatrix>1x:14</TileMatrix>
                        <MinTileRow>0</MinTileRow>
                        <MaxTileRow>16383</MaxTileRow>
                        <MinTileCol>0</MinTileCol>
                        <MaxTileCol>16383</MaxTileCol>
                    </TileMatrixLimits>
        [...]

2021-06-17 16:20 UTC, ahocevar requested changes
This change sets `wrapX` to `true` too aggressively. In the absence of a `wgs84BoundingBox`, you would have to make the same check with the `ows:BoundingBox` of the TileMatrixSet. Otherwise you could have a `TileMatrixSet` of a small region, and because of `wgs84BoundigBox` missing you would incorrectly assume`wrapX`.

2021-06-18 11:32 UTC, ahocevar requested changes

2021-06-18 11:32 UTC, ahocevar commented on src/ol/source/WMTS.js
> +        'EPSG:3857',
You don't know that the `matrixSetExtent` is in `EPSG:3857`. You'd need to get its CRS first.

2021-06-18 12:24 UTC, ahocevar reviewed
Looks good now. Would you be able to add a test for this?

2021-06-21 10:39 UTC, ahocevar approved these changes
Thanks, @M393

2021-06-21 10:40 UTC, merged