Use .transform() instead of .setTransform() when rendering image or text
openlayers/openlayers pull request #14483
Opened 2023-02-05 17:52 UTC by mike-000

Fixes #14478

2023-03-06 19:42 UTC, kevmcgrath commented
Hi @mike-000,

We're eager for this fix, which also addresses #14478 and see that it didn't make it into v7.3. Do you know if there are plans to include it in the next release?  The issue is unfortunately holding up one of our projects.

Kind Regards,
Kevin

2023-03-06 21:04 UTC, ahocevar requested changes
@mike-000 Thanks for this fix. I think what changes for users now is that `postrender` needs to reset any transforms that `prerender` sets. It would be good to test if this is indeed the case, and if so, add at least a paragraph in the release notes.

2023-03-07 11:32 UTC, mike-000 commented
> @mike-000 Thanks for this fix. I think what changes for users now is that `postrender` needs to reset any transforms that `prerender` sets. It would be good to test if this is indeed the case, and if so, add at least a paragraph in the release notes.

In most cases that would already been required - in `drawImageOrLabel()` `setTransform` was called inside a save/restore just as `transform` is now.  Only if the immediate renderer had called `context.setTransform(1, 0, 0, 1, 0, 0)` to revert a previous `setTransform` - which only happened if the style had scale or rotation - would it not have been necessary, but in that case the transform set by the application would not have had the expected effect on the rendering.  For example set the CircleStyle scale to anything other than 1 in https://codesandbox.io/s/feature-move-animation-forked-6vt3o9 and the translated copy of the feature does not appear.

2023-08-14 17:26 UTC, ahocevar commented
@mike-000 Thanks for this fix. Now that we've some backwards incompatible changes lined up already, could you maybe rebase this pull request and move the upgrade notes into the "backwards incompatible changes" section? Thanks in advance!

2023-08-14 17:43 UTC, ahocevar approved these changes
Thanks, @mike-000

2023-08-14 17:54 UTC, merged

2023-08-14 19:27 UTC, kevmcgrath commented
Thank you, @mike-000 and @ahocevar!

2023-08-14 20:28 UTC, tschaub commented
@kevmcgrath - you may know this already, but we create a `dev` tagged release after every merge to the default branch.  So you can get this fix with `npm install ol@dev`.  As mentioned above, we have rolled in some other backwards incompatible changes, so the next stable release will be 8.0.  See the [upgrade notes](https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md) for changes you might need to know about that aren't yet in a stable release.