moved deprecated charcode prop
openlayers/openlayers pull request #14492
Opened 2023-02-07 18:55 UTC by WebKieth

Thanks for [approving](https://github.com/openlayers/openlayers/issues/14490#issuecomment-1419664753) to change unstable code of interaction. Build Checked, feel free to review =)

2023-02-07 20:16 UTC, ahocevar requested changes
Thanks @WebKieth, can you please run `npm run lint --fix` to fix the problems the linter identified?

2023-02-08 03:58 UTC, tschaub approved these changes

2023-02-08 03:59 UTC, tschaub commented
Thanks, @WebKieth

2023-02-08 06:45 UTC, ahocevar approved these changes

2023-02-08 06:45 UTC, merged