From epsg code
openlayers/openlayers pull request #14692
Opened 2023-04-23 21:12 UTC by mike-000

Fixes #14691 
Use epsg.io `wkt` for proj4 definitions instead of proj4 strings where `+nadgrids` currently cannot be handled.

Add an example of using `fromEPSGCode()` via a GeoTIFF siource view options.

2023-04-24 08:12 UTC, ahocevar commented
It has been discussed here already, but I'm unable to find the issue at the moment. The epsg.io API allows to customize what kind of definition you're requesting, and you can say you don't want grid shift transforms. Using WKT instead of a proj string is just an ugly hack in my opinion, so I'm not in favor of this pull request as it is.

2023-04-24 10:13 UTC, mike-000 commented
It was discussed in #14235.as described in #14691.  For EPSG:27700 the solution would be to use https://epsg.io/27700-1314.proj4 instead of https://epsg.io/27700.proj4  To discover that was needed you would first need to run https://epsg.io/?q=27700&format=json&trans=1 and filter the returned transforms to those with `target_crs` 4326 and `grids_list` length 0.  There  is nothing documented in the API https://github.com/maptiler/epsg.io which could do it in a single lookup.

2023-04-24 10:59 UTC, ahocevar commented
I think two lookups would be acceptable. But with help from @klokan, we could do even better: what if epsg.io could provide a download API for the the NTv2 files referenced in the `+nadgrids` param?

2023-04-24 11:34 UTC, mike-000 commented
It would certainly be useful to have a central repository for general use with proj4.  However, some are quite large files (e.g. OSTN15_NTv2_OSGBtoETRS.gsb is almost 15MB).  Using a `+towgs84` definition would be quicker if dynamically defining projections.

2023-04-24 11:43 UTC, klokan commented
+1
We could perhaps make it streamable with HTTP Range request - to download into the client only blocks which are relevant for the required transformation - in parts?

2023-04-24 11:47 UTC, klokan commented
BTW The EPSG Coordinates API is well documented at https://docs.maptiler.com/cloud/api/coordinates/ - this is the one which is supported also for future and which we could improve to provide additional outputs.

2023-04-24 21:19 UTC, ahocevar requested changes

2023-04-24 21:19 UTC, ahocevar commented on src/ol/proj/proj4.js
> +          )[0]?.['code_trans'];
You could sort the results by accuracy, and use the one with the highest accuracy instead of the first.

2023-05-08 10:30 UTC, ahocevar commented
@mike-000: According to @klokan's comment, I think it would make sense to switch to the mentioned Coordinates API.

2023-05-08 10:38 UTC, mike-000 commented
> @mike-000: According to @klokan's comment, I think it would make sense to switch to the mentioned Coordinates API.

That would be a breaking change as it needs an API key.

2023-05-08 11:07 UTC, ahocevar commented
Good point, @mike-000. But using an undocumented API isn't a good solution either. I think the best solution would be to leave things as they are, but provide a ready-made function factory to call with the API key, which users can then pass to `setEPSGLookup()`.

2023-06-18 10:48 UTC, mike-000 commented
The example continues to use the default lookup without an API key as the UTM projection does use `+nadgrids`.  I could add another such as https://codesandbox.io/s/fromepsgcode-maptiler-jn73tq?file=/main.js if one is needed.

2023-06-19 19:59 UTC, ahocevar requested changes
Thanks for your continued effort on this, @mike-000.

Two things that I would change:
* Replace the current example with one that actually uses the `epsgLookupMapTiler()` function
* Use the view returned from the COG as-is, i.e.
   ```js
   setEPSGLookup(epsgLookupMapTiler(key));
   
   // ...
   const map = new Map({
     // ...
     view: cogSource().getView()
   }); 
   ```

2023-06-19 21:40 UTC, mike-000 commented
The minimum needed would be

```
  view: cogSource()
    .getView()
    .then((viewConfig) =>
      fromEPSGCode(viewConfig.projection.getCode()).then(() => viewConfig)
    ),
```

otherwise the projection will not be registered with `proj4` and any other layers will not be reprojected

e.g. https://codesandbox.io/s/fromepsgcode-maptiler-forked-5vcmy9?file=/main.js

2023-06-20 11:30 UTC, ahocevar requested changes

2023-06-20 20:53 UTC, ahocevar approved these changes
Thanks, @mike-000

2023-06-20 20:53 UTC, merged