Add unsnap event
openlayers/openlayers pull request #15494
Opened 2024-01-20 01:34 UTC by eklauberg

Resolve issue: https://github.com/openlayers/openlayers/issues/15404

2024-01-29 13:17 UTC, ahocevar commented on src/ol/events/SnapEvent.js
> +}
This event is not necessary - the `SnapEvent` can be constructed with `SnapEventType.UNSNAP` as first argument.

2024-01-30 08:33 UTC, ahocevar requested changes
Thanks for your contribution, @eklauberg.  See my in-line comments for suggested changes.

2024-01-30 15:09 UTC, eklauberg commented on src/ol/interaction/Snap.js
> +      this.dispatchEvent(new UnsnapEvent());
It seems that these fields (vertex, vertex Pixel, feature, and segment) are all null in the context you mentioned. Should I consider storing the last snap event to send in these fields if needed?

2024-01-30 15:24 UTC, ahocevar commented on src/ol/interaction/Snap.js
> +      this.dispatchEvent(new UnsnapEvent());
Yes, you could store them in the new `snapped_` member. To make the event more useful, I think you'd also have to fire an `unsnap` event when you're still snapped, but to a different vertex, feature or segment. For that, the stored properties would also help.

2024-02-02 10:35 UTC, ahocevar requested changes

2024-02-02 10:35 UTC, ahocevar commented on src/ol/interaction/Snap.js
> +     * @description Holds information about the last snapped state.
```suggestion
     * Holds information about the last snapped state.
     * @type {SnappedInfo|null}
     * @private
```

2024-02-02 10:35 UTC, ahocevar commented on src/ol/interaction/Snap.js
> +      data1.feature?.getId() === data2.feature?.getId()
Features do not need an id, but the feature reference will be the same if the features are the same
```suggestion
      data1.feature === data2.feature
```

2024-02-02 10:35 UTC, ahocevar commented on src/ol/interaction/Snap.js
> +      if (!this.snapped_ || !this.areSnapDataEqual_(this.snapped_, result)) {
Instead of calling `areSnapDataEqual_()` again here, you could store it in a variable above.

2024-02-02 10:35 UTC, ahocevar commented on src/ol/interaction/Snap.js
> +      data1.vertex[1] === data2.vertex[1] &&
I think you'll want to check equality for the segment instead. I'd expect an `unsnap` event only when snapping leaves a segment, not whenever I move the cursor.
```suggestion
      data1.segment === data2.segment &&
```

2025-03-08 01:51 UTC, MoonE commented
Resolved by #16352

2025-03-08 01:51 UTC, closed without merging