Add Unsnap Event
openlayers/openlayers pull request #16352
Opened 2024-11-08 09:47 UTC by RubenKad

Resolve issue: https://github.com/openlayers/openlayers/issues/15404

PR was based on https://github.com/openlayers/openlayers/pull/15494

2024-12-09 13:27 UTC, RubenKad commented
Is there a reason why the review takes a while? Did I miss anything?

2025-01-29 09:32 UTC, RubenKad commented
@ahocevar 
I tried to make a fork of https://github.com/openlayers/openlayers/pull/15494, but that was unfortunately not possible. Therefore, I did some small changes and here are some comments on the review comments of the older PR:
- https://github.com/openlayers/openlayers/pull/15494/files/1bab1e0a76c1628960932460b7ced74a9b1a12c3#r1475855149 -> I changed it to the suggested order
- https://github.com/openlayers/openlayers/pull/15494/files/1bab1e0a76c1628960932460b7ced74a9b1a12c3#r1475871267 and https://github.com/openlayers/openlayers/pull/15494/files/1bab1e0a76c1628960932460b7ced74a9b1a12c3#r1475864287 -> I implemented your suggestions
- https://github.com/openlayers/openlayers/pull/15494/files/1bab1e0a76c1628960932460b7ced74a9b1a12c3#r1475865446 -> This was not relevant anymore. I changed it a bit (in the old PR, only 1 snap event was thrown), such that multiple snap events are always thrown when the cursor moves, similarly as it behaved before.

The other changes are exactly the same, so I hope this is enough information for the review!

2025-01-29 17:42 UTC, ahocevar requested changes
Thanks for the explanations, @RubenKad, now I was able to remember and properly review. The changes look good! Could you please also add a test, to avoid future regressions on this? Also, please run `npm run lint -- --fix` to apply the Prettier fixes.

2025-01-30 18:38 UTC, ahocevar commented on examples/snap.js
> +map.addInteraction(snap);
```suggestion
map.addInteraction(snap);

```

2025-01-30 18:43 UTC, ahocevar approved these changes
Thanks a lot @RubenKad for picking this up and finishing it!

2025-01-30 18:59 UTC, merged